version: '3'

services:

  db:
    build: ./db/
    environment:
      MYSQL_DATABASE: newsletter
      MYSQL_USER: root
      MYSQL_PASSWORD: fatec
      MYSQL_ROOT_PASSWORD: fatec
    volumes:
      - db-data:/var/lib/mysql
    networks:
      - net

  web:
    build: ./app/
    ports:
      - "5000:5000"
    depends_on:
      - db
    networks:
      - net

volumes:
  db-data:


networks:
  net:
    driver: bridge

